const $=s=>document.querySelector(s);
let me=null,leads=[],recipients=[],settingsVersion=1,inviteLink='';
const stages=['New','Contacted','Demo booked','Proposal','Won','Not a fit'];
function status(message,error=false){const el=$('#admin-status');el.textContent=message;el.classList.toggle('error',error);el.hidden=!message}
async function api(url,options={}) {
  const headers={'Content-Type':'application/json',...(options.method && options.method!=='GET' && me?{'x-csrf-token':me.csrfToken}:{}),...options.headers};
  const r=await fetch(url,{...options,headers,signal:AbortSignal.timeout(15000)});const body=await r.json();
  if(!r.ok){if(r.status===401 && me){me=null;showLogin()}throw new Error(body.error || 'Request failed. Try again.')}
  return body;
}
function showOnly(id){for(const section of ['login-panel','setup-panel','activation-panel','dashboard'])$('#'+section).hidden=id!==section;$('#signed-in-name').hidden=id!=='dashboard';$('#logout').hidden=id!=='dashboard'}
function showLogin(){showOnly('login-panel')}
function formRequest(id,endpoint,transform=values=>values){$('#'+id).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));if(values.confirmation!==undefined && values.password!==values.confirmation){status('The passwords do not match.',true);return}const button=form.querySelector('button[type="submit"]');button.disabled=true;try{await api(endpoint,{method:'POST',body:JSON.stringify(transform(values))});form.reset();await enterDashboard();status('You’re signed in.')}catch(err){status(err.message,true)}finally{button.disabled=false}})}
formRequest('login-form','/api/admin/login');formRequest('setup-form','/api/admin/setup');
formRequest('activation-form','/api/admin/activate',values=>({password:values.password,token:location.hash.slice(1)}));
async function enterDashboard(){me=await api('/api/admin/me');if(location.pathname==='/admin/activate')history.replaceState(null,'','/admin');showOnly('dashboard');$('#signed-in-name').textContent=`${me.name} · ${me.role}`;document.querySelectorAll('.owner-only').forEach(el=>el.hidden=me.role!=='owner');await loadLeads()}
$('#logout').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'});me=null;leads=[];$('#lead-list').replaceChildren();showLogin();status('Signed out.')}catch(err){status(err.message,true)}});
$('#refresh-leads').addEventListener('click',()=>loadLeads().catch(err=>status(err.message,true)));
async function loadLeads(){const result=await api('/api/submissions');leads=result.submissions;$('#delivery-warning').hidden=result.notificationsConfigured;$('#metric-total').textContent=leads.length;$('#metric-new').textContent=leads.filter(l=>l.stage==='New').length;$('#metric-demos').textContent=leads.filter(l=>l.stage==='Demo booked').length;$('#metric-won').textContent=leads.filter(l=>l.stage==='Won').length;renderLeads()}
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
function field(labelText,el){const label=node('label','',labelText);label.append(el);return label}
function renderLeads(){const q=$('#lead-search').value.toLowerCase(),stage=$('#lead-stage').value;const filtered=leads.filter(l=>(!stage || l.stage===stage) && (!q || [l.name,l.salon,l.email,l.services,l.assigned_to].some(v=>(v || '').toLowerCase().includes(q))));$('#lead-list').replaceChildren();$('#lead-count').textContent=`${filtered.length} of ${leads.length} saved enquiries shown`;for(const lead of filtered)$('#lead-list').append(leadCard(lead));if(!filtered.length)$('#lead-list').append(node('p','empty-message',leads.length?'No matching enquiries. Change the filter.':'No enquiries yet. New website submissions will appear here.'))}
function leadCard(lead) {
  const leadLabel=lead.salon || lead.name;
  const card=node('article','lead-card'),heading=node('div','lead-heading');
  heading.append(node('h2','',leadLabel),node('span','record-tag',lead.stage));card.append(heading,node('p','',`#${lead.id} · ${new Date(lead.submitted_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} Pacific`));
  const contact=node('div','lead-contact');contact.append(node('p','',`${lead.name} · ${lead.business_type || 'Not supplied'}`));const email=node('a','',lead.email);email.href='mailto:'+encodeURIComponent(lead.email);contact.append(email);
  if(lead.phone){const p=node('p');const phone=node('a','',lead.phone);phone.href='tel:'+lead.phone.replace(/[^+\d]/g,'');p.append(phone);contact.append(p)}
  contact.append(node('p','',`Preferred reply: ${lead.contact_preference || 'Email'} · Booking: ${lead.booking_system || 'Not supplied'}`));card.append(contact);
  card.append(node('p','',lead.services || 'No workflow detail supplied.'));if(lead.pain_points)card.append(node('p','',lead.pain_points));if(lead.source)card.append(node('p','',`Source: ${lead.source}`));
  const delivery=node('div','lead-notifications');delivery.textContent='Email alerts: '+(lead.notifications.length?lead.notifications.map(n=>`${n.recipient} — ${n.status==='sent'?'accepted by mail provider':`${n.status} (attempts: ${n.attempts})`}`).join('; '):'No queued recipients');card.append(delivery);
  const edit=node('form','admin-form'),grid=node('div','lead-edit-grid');const select=node('select');select.setAttribute('aria-label',`Stage for ${leadLabel}`);for(const stage of stages){const opt=node('option','',stage);opt.value=stage;opt.selected=lead.stage===stage;select.append(opt)}
  const owner=node('input');owner.value=lead.assigned_to || '';owner.maxLength=120;owner.placeholder='Who will follow up?';owner.setAttribute('aria-label',`Follow-up owner for ${leadLabel}`);
  grid.append(field('Stage',select),field('Follow-up owner',owner));const notes=node('textarea');notes.value=lead.notes || '';notes.maxLength=4000;notes.rows=3;notes.setAttribute('aria-label',`Notes for ${leadLabel}`);const noteLabel=field('Conversation notes',notes);noteLabel.className='full-width';grid.append(noteLabel);edit.append(grid);
  const actions=node('div','button-row'),save=node('button','button small','Save changes →'),claim=node('button','text-button','Assign to me');save.type='submit';claim.type='button';claim.addEventListener('click',()=>owner.value=me.name);actions.append(save,claim);edit.append(actions);
  edit.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{const r=await api(`/api/submissions/${lead.id}`,{method:'PATCH',body:JSON.stringify({stage:select.value,assignedTo:owner.value,notes:notes.value,version:lead.version})});Object.assign(lead,r.lead);heading.lastChild.textContent=lead.stage;status(`Saved enquiry #${lead.id}.`);$('#metric-new').textContent=leads.filter(l=>l.stage==='New').length;$('#metric-demos').textContent=leads.filter(l=>l.stage==='Demo booked').length;$('#metric-won').textContent=leads.filter(l=>l.stage==='Won').length}catch(err){status(err.message,true)}finally{save.disabled=false}});card.append(edit);return card;
}
$('#lead-search').addEventListener('input',renderLeads);$('#lead-stage').addEventListener('change',renderLeads);
document.querySelectorAll('.admin-tab').forEach(button=>button.addEventListener('click',async()=>{const panel=button.dataset.panel;document.querySelectorAll('.admin-tab').forEach(b=>b.classList.toggle('active',b===button));for(const name of ['leads','notifications','team'])$('#panel-'+name).hidden=name!==panel;try{if(panel==='notifications')await loadRecipients();if(panel==='team')await loadTeam()}catch(err){status(err.message,true)}}));
async function loadRecipients(){const r=await api('/api/admin/notifications');recipients=[...r.emails];settingsVersion=r.version;renderRecipients()}
function renderRecipients(){$('#recipient-list').replaceChildren();for(const email of recipients){const row=node('div','recipient-row');row.append(node('span','',email));const remove=node('button','','Remove');remove.type='button';remove.addEventListener('click',()=>{if(recipients.length===1){status('Keep at least one recipient.',true);return}recipients=recipients.filter(v=>v!==email);renderRecipients()});row.append(remove);$('#recipient-list').append(row)}}
$('#add-recipient').addEventListener('click',()=>{const input=$('#recipient-email'),value=input.value.trim().toLowerCase();if(!value || !input.checkValidity()){input.reportValidity();status('Enter a valid partner email.',true);return}if(recipients.length>=10){status('The maximum is ten recipients.',true);return}if(!recipients.includes(value))recipients.push(value);input.value='';renderRecipients()});
$('#save-recipients').addEventListener('click',async e=>{e.currentTarget.disabled=true;try{const r=await api('/api/admin/notifications',{method:'PUT',body:JSON.stringify({emails:recipients,version:settingsVersion})});recipients=r.emails;settingsVersion=r.version;renderRecipients();status('Notification recipients saved for future enquiries.')}catch(err){status(err.message,true)}finally{e.currentTarget.disabled=false}});
async function loadTeam(){const r=await api('/api/admin/team');$('#team-list').replaceChildren();for(const user of r.users){const row=node('div','team-row'),name=node('div','team-name',`${user.name} · ${user.role}${user.active?'':' · inactive'}`);name.append(node('span','team-email',user.email));row.append(name);if(user.role==='admin'){const toggle=node('button','',user.active?'Disable access':'Enable access');toggle.type='button';toggle.addEventListener('click',async()=>{toggle.disabled=true;try{await api(`/api/admin/team/${user.id}`,{method:'PATCH',body:JSON.stringify({active:!user.active})});await loadTeam();status('Team access updated.')}catch(err){status(err.message,true);toggle.disabled=false}});row.append(toggle)}$('#team-list').append(row)}}
$('#invite-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const button=form.querySelector('button');button.disabled=true;try{const r=await api('/api/admin/invites',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});inviteLink=new URL(r.activationPath,location.origin).href;$('#invite-url').textContent=inviteLink;$('#invite-url').href=inviteLink;$('#invite-result').hidden=false;status('Invitation created. Share it directly with your partner.')}catch(err){status(err.message,true)}finally{button.disabled=false}});
$('#copy-invite').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(inviteLink);status('Invitation link copied.')}catch{status('Select the invitation link and copy it manually.')}});
async function init(){if(location.pathname==='/admin/activate' && location.hash){showOnly('activation-panel');return}try{await enterDashboard()}catch(err){if(me){status(err.message,true);return}me=null;try{const info=await api('/api/admin/setup-info');if(info.setupNeeded && info.available){showOnly('setup-panel')}else{showLogin();if(info.setupNeeded)status('Owner setup needs ADMIN_SETUP_TOKEN in Railway. Configure a random key of at least 32 characters, then reload.',true);if(!info.available && !info.setupNeeded)status('If you already have an account, sign in.',false)}}catch(err){showLogin();status(err.message,true)}}}
init();
